name: "xupt-scholarship"
port: 8096
logsAddress: "./logs/"

mysql:
  name: "root"
  host: "123.56.239.54"
  port: 3306
  password: "586014BZYbzy"
  dbName: "xupt-scholarship"

redis:
  host: "123.56.239.54"
  port: 6379