name: "xupt-scholarship"
port: 8096
logsAddress: "./logs/"

mysql:
  name: "root"
  host: "127.0.0.1"
  port: 3306
  password: "586014BZYbzy"
  dbName: "xupt-scholarship"

redis:
  host: "127.0.0.1"
  port: 6379